### ISSUE TITLE
Attachment remove and Image remove icons should change to a hand when hover!

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#59] opened 2019-08-19 11:23 UTC
In original Joomla (Protostar) template:
all images with links or events show a hand when you mouseover,
only attachment remove (and image remove) show an arrow (and change never to a hand)
It would be better if there would appear a hand! It helps the user.

**Comment by depebo** [comment] 2019-08-20 11:54
will be done in the next release, duplicate of #41

**Closed as completed by depebo** 2019-08-20 11:54 UTC
