### ISSUE TITLE
pkg_jem_v2.3.0-dev0.4.6: currently no attendances in attendees is wrong

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#30] opened 2019-05-06 13:10 UTC
![attendees](https://user-images.githubusercontent.com/2960236/57375052-af378900-719c-11e9-9e03-30cbc5ee6dba.png)
event when there are attendances, the attendees window shows
"currently no attendances"

**Comment by Egnarts94** [comment] 2019-05-10 09:49
Eventually you need to clear your webspace manually. After moving the files in the views to /tmpl/responsive the old ones are not deleted.

For me, I can not reproduce you problem. Eventually you should update to the current build.
In https://github.com/Egnarts94/JEM-Project/releases I will publish new testbuilds in future.

**Comment by jojo12** [comment] 2019-05-17 05:49
dev4.1: sorry, but the problem persists!
in the event detail view, they are shown, but in the attendees manager not!

**Comment by Egnarts94** [comment] 2019-05-18 18:40
For me, it works
![image](https://user-images.githubusercontent.com/14231804/57973675-00b9f200-79ad-11e9-9c0b-dd5c5ef4bfc5.png)

Am I in the correct place?
Event -> Registration -> Booked Places -> Click on Link

Did you do this?
>Eventually you need to clear your webspace manually. After moving the files in the views to >/tmpl/responsive the old ones are not deleted.

**Comment by jojo12** [comment] 2019-05-19 13:39
Ups: it' s a bit more complicated:
The settings were: show attendee names for everyone/show all related users=no
Then the super admin was registrated to attend.
in eventdetail the cbavatar and name was shown, but in the attendees manager in Frontend, there was "Currently no attendances..."

Now I added more persons, one on waitinglist, one invited. 

I changed to show all related users=yes.
Now in the eventdetail and in the attendees manager in Frontend the attending users are shown.

(Perhaps I did not understand well the "show all related users"!!)

**Comment by Egnarts94** [comment] 2019-05-20 20:16
So, does it work as expected?
Do we need to change something?

> The settings were: show attendee names for everyone/show all related users=no
> Then the super admin was registrated to attend.
> in eventdetail the cbavatar and name was shown, but in the attendees manager in Frontend, there was > "Currently no attendances..."

That seems to be a bug, isn't it? Normally the "show all reladed users" setting shouldn't have impact in the attendee manager.

**Comment by jojo12** [comment] 2019-05-20 20:28
Yes, I think, this is the /a bug!

**Comment by Egnarts94** [comment] 2019-07-03 12:55
> The settings were: show attendee names for everyone/show all related users=no
> Then the super admin was registrated to attend.
> in eventdetail the cbavatar and name was shown, but in the attendees manager in Frontend, there was > "Currently no attendances..."

I tried to reproduce the bug with the following steps:
1. JEM -> Settings -> Event Page -> Show Attendee Names to "Everybody", and Show all related users "No", Selected Community Solution "CB" and Select Integration Option "Link to profile and show avatar"
2. As superuser create Testevent with registration, allow annulation, max places 0
3. Attend to the event from another browser via a normal registered user.
4. In the browser of the superuser, the attending user is shown in the event and on the attendees manager when clicking on "Booked places".

So what I need to do to reproduce?

**Comment by JKoelman** [comment] 2019-07-20 16:38
To add....   

Did install JEM2.3.0-dev0.4.6  and noticed an issue with the attending-part too.

- did add an event
- did add 3 people to an event (1 is superuser)
- then a menu-item to my attending view
- in front i'm seeing only seeing 1 row + in the row status an icon with status "user is invited"

Will check later a bit more....  also not sure if it's related to your responsive pull.  If it's not then it would be better to add the issue to jemproject repo.

**Comment by JKoelman** [comment] 2019-07-20 17:50
Right to add..

- installed version JEM 2.3.0-dev04.6
- Responsive view setting
- Added users to event (super user + 2x test user)
- created a menu-link to myevents-view
- logged in front as super user then when to myevents
- in there the layout was a bit messed up
first i did think there were no link to the attendees-view but after second look it seems that the numbers are at the left.

second problem:  when the link to the attendees-view is pressed it gives a problem
` Call to undefined method JemOutput::addremovebutton() `



![Knipsel-myevents-20190720-layoutproblem](https://user-images.githubusercontent.com/2514855/61582145-47e86e80-ab27-11e9-965a-55c8e8047ef4.PNG)

**Comment by depebo** [comment] 2019-07-22 09:36
@JKoelman please confirm the issue still present in the latest release

**Comment by JKoelman** [comment] 2019-07-27 18:28
whoops just reads your message (it's currently to hot weather here).. Have to check with the latest code, to be sure so can't tell right now.   Thing is that i did test with 0.4.6 as that was with the pull. @Egnarts94  @depebo  will check but that will be at later point.   

Think we first have to check/decide if the pull can be merged.  There will be small things that have to be fixed but when it's merged the issues can be mentioned at the jemproject repo too.

**Comment by depebo** [comment] 2019-08-16 12:07
@JKoelman @Egnarts94 I think I understand what @jojo12 was referring to: if you set the filter for non-existing attendees, then no attendees are shown, but also filter controls are not shown, so there is no way to get out from that "currently no attendances..." situation. There was a Joomla! similar bug with contact list view, where display of filter controls was dependent on records count: if count was zero, then nothing was displayed, not event filter controls.
@jojo12 - Am I getting close?

**Comment by depebo** [comment] 2019-08-20 13:35
display filter options even if no attendees found - to allow user get out from filter, which resulted in 0 attendees returned
Will be done in the next release

**Closed as completed** 2019-08-20 16:06 UTC
Labels: bug
